import assert from 'node:assert/strict';
process.env.ANTHROPIC_API_KEY='offline-fixture';
process.env.BOT_WEB_SEARCH='off';
process.env.BOT_USAGE_LOG='off';
const {isPriorityCommenter,isLowEngagementSkip,conversationReplyIssue}=await import('../src/supporter-replies');
const {classifyAndDraft}=await import('../src/reply');
const {config}=await import('../src/config');
for(const name of ['tgeorgekoshy','ruth.werner.9','@RUTH.WERNER.9']) assert.equal(isPriorityCommenter(name,config.priorityUsernames),true);
for(const name of [undefined,'ruth.werner.9.fake','other']) assert.equal(isPriorityCommenter(name,config.priorityUsernames),false);
assert.equal(isLowEngagementSkip('skip','other','A lone emoji with no substantive content'),true);
for(const reason of ['diagnosis before reveal','owner response required','unclear GIF meaning','error: timeout','spam','non-English','guard:forced-skip']) assert.equal(isLowEngagementSkip('skip','other',reason),false);
assert.equal(conversationReplyIssue('It almost looks parasitic','banter','This one is self-inflicted dust doing its work.',true),'unsupported blame or patient motivation');
assert.equal(conversationReplyIssue('Inhaled talcum powder as a baby.','empathize',"That's a worrying start for your lungs.",true),'assumed personal medical history');
assert.equal(conversationReplyIssue('I inhaled powder as a baby.','empathize','That sounds like a frightening experience.',true),undefined);
assert.equal(conversationReplyIssue('Mold','correct','Fungal infections can produce nodular patterns but the upper-lobe conglomerate masses and calcified hilar nodes here point toward progressive massive fibrosis from long-term dust exposure rather than mold.',true),'overlong response to a short guess');

const base={intent:'friendly reaction',decision:'reply',category:'banter',reply_text:'That one was rough to look at.',reason:'acknowledge their reaction',needs_lookup:false,promo_product:'none',promo_explicit:false};
let queue:any[]=[];let calls=0;let body:any;
globalThis.fetch=async (_url,init)=>{
 calls++;body=JSON.parse(String(init?.body));const next=queue.shift();assert.ok(next,'unexpected extra paid call');
 return new Response(JSON.stringify({id:'fixture',type:'message',role:'assistant',model:config.triageModel,stop_reason:'tool_use',usage:{input_tokens:1,output_tokens:1},content:[{type:'tool_use',id:'tool',name:'submit_reply',input:next}]}),{headers:{'content-type':'application/json'}});
};
const input={postText:'Diagnosis challenge',commentText:'😮',answer:'Progressive massive fibrosis',answerPublic:true,priorityCommenter:true,modelOverride:config.triageModel};
queue=[base];calls=0;
assert.equal((await classifyAndDraft(input)).decision,'reply');assert.equal(calls,1);
assert.match(JSON.stringify(body),/OWNER REPLY PRIORITY/);
const low={...base,decision:'skip',category:'other',reply_text:'',reason:'A lone emoji with no substantive content'};
queue=[low,base];calls=0;assert.equal((await classifyAndDraft(input)).decision,'reply');assert.equal(calls,2);
queue=[low,low];calls=0;const held=await classifyAndDraft(input);assert.equal(held.decision,'skip');assert.equal(held.category,'other');assert.equal(calls,2);
queue=[low];calls=0;await classifyAndDraft({...input,priorityCommenter:false});assert.equal(calls,1);assert.ok(!JSON.stringify(body).includes('OWNER REPLY PRIORITY'));
queue=[{...base,category:'affirm',reply_text:"That's the one."}];calls=0;
assert.equal((await classifyAndDraft({...input,commentText:'Progressive massive fibrosis?',answerPublic:false})).decision,'skip');assert.equal(calls,1);
queue=[];calls=0;assert.equal((await classifyAndDraft({...input,commentText:'Are you a bot?'})).decision,'skip');assert.equal(calls,0);
queue=[{...base,category:'personal_medical',reply_text:'You should get a scan.'}];
assert.equal((await classifyAndDraft({...input,commentText:'My child is drooling. Should I get an X-ray?'})).category,'personal_medical');assert.equal(calls,1);
queue=[{...base,reply_text:"That's a worrying start for your lungs."},{...base,reply_text:'The case points to a different kind of dust exposure.'}];calls=0;
assert.equal((await classifyAndDraft({...input,commentText:'Inhaled talcum powder as a baby.'})).decision,'reply');assert.equal(calls,2);
queue=[{...base,reply_text:'This was self-inflicted.'},{...base,reply_text:'This was self-inflicted.'}];calls=0;
assert.equal((await classifyAndDraft({...input,commentText:'It almost looks parasitic'})).decision,'skip');assert.equal(calls,2);
console.log('PASS exact supporter matching, priority prompt, one shared repair, cached failures, reveal/advice/operator safeguards and September 20 reply regressions');
