import assert from 'node:assert/strict';
process.env.ANTHROPIC_API_KEY = 'offline-fixture';
process.env.BOT_USAGE_LOG = 'off';
let calls = 0;
let failAgain = false;
globalThis.fetch = async (_url, init) => {
  calls++;
  const body = JSON.parse(String(init?.body));
  if (calls === 2) assert.match(JSON.stringify(body.messages), /STYLE RECHECK/);
  return new Response(JSON.stringify({id:'fixture',type:'message',role:'assistant',model:body.model,stop_reason:'tool_use',stop_sequence:null,usage:{input_tokens:1,output_tokens:1},content:[{type:'tool_use',id:'fixture',name:'submit_reply',input:{intent:'joke',decision:'reply',category:'banter',reply_text:calls === 1 || failAgain ? 'Coins went in; nothing came out.' : 'Worst vending machine ever.',reason:'joke',needs_lookup:false,promo_product:'none',promo_explicit:false}}]}), {headers:{'content-type':'application/json'}});
};
const { classifyAndDraft } = await import('../src/reply');
const { config } = await import('../src/config');
const input = {postText:'Case',commentText:'A vending machine?',answerPublic:true,modelOverride:config.triageModel};
assert.equal((await classifyAndDraft(input)).reply_text, 'Worst vending machine ever.');
assert.equal(calls, 2);
calls = 0;
failAgain = true;
const held = await classifyAndDraft(input);
assert.equal(calls, 2);
assert.equal(held.decision, 'skip');
assert.equal(held.category, 'other');
assert.equal(held.reply_text, '');
console.log('PASS one style recheck maximum; repeated failure is empty and cacheable');
